# Generated by Django 3.0 on 2020-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=100)),
                ('govt_id', models.CharField(default='', editable=False, max_length=100)),
                ('email_id', models.EmailField(default='', editable=False, max_length=254, verbose_name=' ')),
                ('password', models.CharField(default='', editable=False, max_length=20, verbose_name=' ')),
            ],
        ),
    ]
